apiVersion: v1
kind: Service
metadata:
  labels:
    name: vod-simulator
  name: vod-simulator
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "1234"
    prometheus.io/probe: "true"
spec:
  type: NodePort
  ports:
    # The port that this service should serve on.
    - name: vod-8081
      port: 8081
      targetPort: 8081
      nodePort: 30881
    - name: metrics-1234
      port: 1234
      targetPort: 1234
      nodePort: 31234
  selector:
    name: vod-simulator
