apiVersion: v1
kind: ReplicationController
metadata:
  name: prom-gateway
  labels:
    name: prom-gateway
spec:
  replicas: 1
  selector:
    name: prom-gateway
  template:
    metadata:
      labels:
        name: prom-gateway
    spec:
      containers:
      - name: prom-gateway
        image: prom/pushgateway
        ports:
          - containerPort: 9091
